WebsiteFashion/Models/CheckoutViewModel.cs
namespace WebsiteFashion.Models
{
    public class CheckoutViewModel
    {
        public Order Order { get; set; }
        public decimal DiscountAmount { get; set; }
    }
}

WebsiteFashion/Models/OrderDetail.cs
 namespace WebsiteFashion.Models
{
    public class OrderDetail
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public Order Order { get; set; }
        public Product Product { get; set; }
    }
}

WebsiteFashion/Models/ShoppingCart.cs
namespace WebsiteFashion.Models
{
    public class ShoppingCart
    {
        public List<CartItem> Items { get; set; } = new List<CartItem>();

        public void AddItem(CartItem item)
        {
            var existingItem = Items.FirstOrDefault(i => i.ProductId ==
            item.ProductId);
            if (existingItem != null)
            {
                existingItem.Quantity += item.Quantity;
            }
            else
            {
                Items.Add(item);
            }
        }
        public void RemoveItem(int productId)
        {
            Items.RemoveAll(i => i.ProductId == productId);
        }

    }
}

WebsiteFashion/Controllers/CouponController.cs
using Microsoft.AspNetCore.Mvc;
using WebsiteFashion.Repositories;
using WebsiteFashion.Models;
using WebsiteFashion.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebsiteFashion.Controllers
{
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICouponRepository _couponRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IProductRepository _productRepository;
        

        public CouponController(ICouponRepository couponRepository, ApplicationDbContext context, ICategoryRepository categoryRepository, IProductRepository productRepository)
        {
            _couponRepository = couponRepository;
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
            _context = context;
        }

        public ActionResult CouponView(ShoppingCart cart)
        {
            ViewBag.ShoppingCart = cart;
            return View();
        }

        public async Task<IActionResult> Index()
        {
            var coupons = await _couponRepository.GetAllAsync();
            var categories = await _categoryRepository.GetAllAsync();
            return View((coupons, categories));
        }

        public async Task<IActionResult> ChooseCoupon()
        {
            var coupons = await _couponRepository.GetAllAsync();
            var categories = await _categoryRepository.GetAllAsync();
            var products = await _productRepository.GetAllAsync();

            

            return View((coupons, categories, products));
        }

        [Authorize(Roles = "Admin, Employee")]
        public async Task<IActionResult> AddAsync()
        {
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View();
        }

        [Authorize(Roles = "Admin, Employee")]
        [HttpPost]
        public async Task<IActionResult> Add(Coupon coupon)
        {
            if (ModelState.IsValid)
            {
                await _couponRepository.AddAsync(coupon);
                return RedirectToAction(nameof(Index));
            }
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View(coupon);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var coupon = await _couponRepository.GetByIdAsync(id);
            if (coupon == null)
            {
                return NotFound();
            }

            return View(coupon);
        }

        // POST: /Coupon/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var coupon = await _couponRepository.GetByIdAsync(id);
            if (coupon == null)
            {
                return NotFound(); // Coupon not found
            }

            await _couponRepository.DeleteAsync(coupon.Id);

            return RedirectToAction(nameof(Index));
        }
        [AllowAnonymous]
        /*        public async Task<IActionResult> Display(int id)
                {
                    var coupon = await _couponRepository.GetByIdAsync(id);
                    var categories = await _categoryRepository.GetAllAsync();

                    if (coupon == null)
                    {
                        return NotFound();
                    }
                    return View(coupon);
                }*/
        public async Task<IActionResult> Display(int id)
        {
            var coupon = await _couponRepository.GetByIdAsync(id);

            if (coupon == null)
            {
                return NotFound();
            }

            // Fetch the category associated with the coupon
            var category = await _categoryRepository.GetByIdAsync(coupon.CategoryId);

            if (category == null)
            {
                // Handle the case where the associated category is not found
                return NotFound("Category not found for the coupon.");
            }

            // You can add the category name to the coupon object or create a view model to pass both coupon and category
            coupon.Category.Name = category.Name;

            return View(coupon);
        }


        // Hiển thị form cập nhật sản phẩm
        public async Task<IActionResult> Update(int id)
        {
            var coupon = await _couponRepository.GetByIdAsync(id);
            if (coupon == null) 
            {
                return NotFound();
            }
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name",coupon.CategoryId);

            return View(coupon);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Employee")]
        public async Task<IActionResult> Update(int id, Coupon coupon)
        {
            if (id != coupon.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                await _couponRepository.UpdateAsync(coupon);
                return RedirectToAction(nameof(Index));
            }
            return View(coupon);
        }
    }
}

WebsiteFashion/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using WebsiteFashion.Models;
using WebsiteFashion.Repositories;
using WebsiteFashion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.Data.SqlClient;


namespace WebsiteFashion.Controllers
{


    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ICouponRepository _couponRepository;

        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository, ApplicationDbContext context, ICouponRepository couponRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _couponRepository = couponRepository;
            _context = context;
        }

        public async Task<IActionResult> Index(string? searchString, string? categoryName, string sortOrder)
        {
            var allProducts = _context.Products.AsQueryable();
            var allCategories = _context.Categories.AsQueryable();
            var allCoupons = _context.Coupon.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                string lowercaseSearchString = searchString.ToLower();
                allProducts = allProducts.Where(p => p.Name.ToLower().Contains(lowercaseSearchString));
            }

            if (!string.IsNullOrEmpty(categoryName))
            {
                allProducts = allProducts.Where(p => p.Category.Name.ToLower() == categoryName.ToLower());
            }

            // Search theo tăng giảm giá
            switch (sortOrder)
            {
                case "price_asc":
                    allProducts = allProducts.OrderBy(p => p.Price);
                    break;
                case "price_desc":
                    allProducts = allProducts.OrderByDescending(p => p.Price);
                    break;
                default:
                    break;
            }

            // Kiểm tra nếu là role của Customer
            if (User.IsInRole("Customer"))
            {
                // Lọc ra những sản phẩm không bị vô hiệu hoa
                allProducts = allProducts.Where(p => !p.IsDetactive);
            }

            // Fetch all data
            var products = await allProducts.ToListAsync();
            var categories = await allCategories.ToListAsync();
            var coupons = await allCoupons.ToListAsync();

            var viewModel = new ProductCategoryViewModel
            {
                Products = products,
                Categories = categories,
                Coupons = coupons
            };

            return View(viewModel);
        }


        [HttpPost]
        public JsonResult GetSearchValue(string search)
        {
            var productResult = _context.Products.Where(x => x.Name.Contains(search))
                                        .Select(x => new
                                        {
                                            label = x.Name,
                                            value = x.Name,
                                        }).ToList();
            return Json(productResult);
        }
        [HttpPost]
        public JsonResult GetSearchCategoryValue(string search)
        {
            var productResult = _context.Categories.Where(x => x.Name.Contains(search))
                                        .Select(x => new
                                        {
                                            label = x.Name,
                                            value = x.Name,
                                        }).ToList();
            return Json(productResult);
        }


        [Authorize(Roles = "Admin, Employee")]
        public async Task<IActionResult> AddAsync()
        {
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View();
        }

        // Add product
        [Authorize(Roles = "Admin, Employee")]
        [HttpPost]
        public async Task<IActionResult> Add(Product product, IFormFile imageUrl, List<IFormFile> imageUrls)
        {
            if (ModelState.IsValid)
            {
                if (imageUrl != null)
                {
                    // Lưu hình ảnh đại diện
                    product.ImageUrl = await SaveImage(imageUrl);
                }

                if (imageUrls != null)
                {
                    product.ImageUrls = new List<string>();
                    foreach (var file in imageUrls)
                    {
                        // Lưu các hình ảnh khác
                        product.ImageUrls.Add(await SaveImage(file));
                    }
                }

                await _productRepository.AddAsync(product);
                return RedirectToAction(nameof(Index));
            }
            // Nếu ModelState không hợp lệ, hiển thị form với dữ liệu đã nhập
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            return View(product);
        }

        private async Task<string> SaveImage(IFormFile image)
        {
            var savePath = Path.Combine("wwwroot/images", image.FileName); // Thay đổi đường dẫn theo cấu hình của bạn
            using (var fileStream = new FileStream(savePath, FileMode.Create))
            {
                await image.CopyToAsync(fileStream);
            }
            return "/images/" + image.FileName; // Trả về đường dẫn tương đối
        }
        private async Task<Product> GetProductFromDatabase(int productId)
        {
            // Truy vấn cơ sở dữ liệu để lấy thông tin sản phẩm
            var product = await _productRepository.GetByIdAsync(productId);
            return product;
        }

        // Hiển thị thông tin chi tiết sản phẩm
        public async Task<IActionResult> Display(int productId)
        {
            if (productId == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == productId);

            if (product == null)
            {
                return NotFound();
            }

            // Check if the user is in the "Customer" role and the product is inactive
            if (User.IsInRole("Customer") && product.IsDetactive == true)
            {
                // Redirect the customer to a page that explains the product is not available
                return RedirectToAction("ProductNotAvailable", "Home");
            }

            return View(product);
        }



        // Hiển thị form cập nhật sản phẩm
        [Authorize(Roles = "Admin, Employee")]
        public async Task<IActionResult> Update(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            var categories = await _categoryRepository.GetAllAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name", product.CategoryId);
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                await _productRepository.UpdateAsync(product);
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }


        // Hiển thị form xác nhận xóa sản phẩm
        [Authorize(Roles = "Admin, Employee")]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // Xử lý xóa sản phẩm
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _productRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Employee")]
        public async Task<IActionResult> DeleteAll()
        {
            var products = await _productRepository.GetAllAsync();
            if (products == null)
            {
                return NotFound();
            }
            else
            {
                foreach (var product in products)
                {
                    await _productRepository.DeleteAsync(product.Id);
                }
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Employee")]
        public async Task<IActionResult> DeactivateProduct(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            product.IsDetactive = true;
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Employee")]

        public async Task<IActionResult> ReactivateProduct(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            product.IsDetactive = false;
            await _context.SaveChangesAsync();

WebsiteFashion/Views/ShoppingCart/Checkout.cshtml
@model ValueTuple<Order, decimal >

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var form = document.querySelector('form');
            form.addEventListener('submit', function (event) {
                var requiredFields = form.querySelectorAll('[required]');
                var isValid = true;

                requiredFields.forEach(function (field) {
                    if (field.value.trim() === '') {
                        isValid = false;
                        alert('Please fill out all required fields.');
                        event.preventDefault();
                        return;
                    }
                });

                if (!isValid) {
                    event.preventDefault();
                }
            });
        });
    </script>
}

<h2>Checkout</h2>
<form asp-action="Checkout" method="post">
    <input type="hidden" name="discountTotal" value="@Model.Item2" />
    <div class="form-group">
        <label asp-for="@Model.Item1.ShippingAddress">Shipping Address</label>
        <input asp-for="@Model.Item1.ShippingAddress" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="@Model.Item1.Notes">Notes</label>
        <textarea asp-for="@Model.Item1.Notes" class="form-control" required></textarea>
    </div>
    <div class="form-group">
        <button type="submit" name="payment" value="Thanh toán COD" class="btn btn-primary text-uppercase text-black w-100 mt-2">Thanh toán COD</button>
        <button type="submit" name="payment" value="Thanh toán VNPay" class="btn border-secondary text-uppercase text-primary w-100 mt-2">Thanh toán VNPay</button>
    </div>
</form>

WebsiteFashion/Views/ShoppingCart/Index.cshtml
@* @model ShoppingCart *@
@* @model ValueTuple<ShoppingCart, IEnumerable<Coupon>, IEnumerable<Product>, IEnumerable<Category>> *@
@* @model Tuple<ShoppingCart, IEnumerable<Coupon>, IEnumerable<Product>, IEnumerable<Category>> *@
@model Tuple<WebsiteFashion.Models.ShoppingCart, IEnumerable<WebsiteFashion.Models.Coupon>, IEnumerable<WebsiteFashion.Models.Product>, IEnumerable<WebsiteFashion.Models.Category>>


@{
    decimal sumTotal = 0;
    decimal discountTotal = 0;
    decimal discount = 0;
    decimal cost = 0;
}

@*Gio hang*@
<h2 class="my-4">Giỏ hàng của bạn</h2>

<form method="post" asp-action="RemoveAllFromCart">
    <button type="submit" class="btn btn-danger">
        Xóa hết
    </button>
</form>

<table class="table table-striped border-bottom">
    <thead class="thead-dark">
        <tr>
            <th>Hình ảnh</th>
            <th>Sản phẩm</th>
            <th>Loai</th>
            <th>Số lượng</th>
            <th>Giá</th>
            <th>Tạm tính</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Item1.Items)
        {
            <tr class="justify-content-between align-items-center">
                <td>
                    <a class="text-decoration-none text-black" asp-controller="Product" asp-action="Display" asp-route-productId="@item.ProductId">
                        <img src="@item.ImageUrl" alt="@item.Name" style="width:100px;height:auto;">
                    </a>
                </td>
                <td>
                    <a class="text-decoration-none text-black" asp-controller="Product" asp-action="Display" asp-route-productId="@item.ProductId">
                        @Html.DisplayFor(modelItem => item.Name)
                    </a>
                </td>
                <td>
                    <a class="text-decoration-none text-black" asp-controller="Product" asp-action="Display" asp-route-productId="@item.ProductId">
                        @Model.Item4.FirstOrDefault(c => c.Id == item.CategoryId)?.Name
                    </a>
                </td>
                <td>
                    <form asp-controller="ShoppingCart" asp-action="UpdateQuantity" method="post">
                        <input type="hidden" name="productId" value="@item.ProductId" />
                        <input type="number" name="quantity" value="@item.Quantity" min="1" />
                        <button type="submit" class="btn btn-info btn-sm">Cập nhật</button>
                    </form>
                </td>
                <td>@Html.DisplayFor(modelItem => item.Price)</td>
                <td>@(item.Price * item.Quantity)</td>
                <td>
                    <a asp-action="RemoveFromCart" asp-route-productId="@item.ProductId" class="btn btn-danger btn-sm">Xóa</a>
                </td>
            </tr>
            sumTotal += (item.Price * item.Quantity);
        }
    </tbody>
</table>

@* Choose Vouchers *@
<h2>Vouchers</h2>
<a asp-controller="Coupon" asp-action="ChooseCoupon">
    <button class="btn btn-outline-dark">
        <i class="bi bi-bag-plus-fill me-1"></i> Add vouchers
    </button>
</a>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Id</th>
            <th>Code</th>
            <th>Category</th>
            <th>Amount</th>
            <th>Discount</th>
            <th>Start Date</th>
            <th>End Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var coupon in Model.Item2)
        {


            <tr class="justify-content-between align-items-center ">
                <td>
                    <span>@coupon.Id</span>
                </td>
                <td>
                    <span>
                        @coupon.Code
                    </span>
                </td>
                <td>
                    <span>
                        @Model.Item4.FirstOrDefault(c => c.Id == coupon.CategoryId)?.Name
                    </span>
                </td>
                <td>
                    <span>
                        @coupon.Amount
                    </span>
                </td>
                <td>
                    <span>
                        @((int)coupon.Discount) %
                    </span>
                </td>
                <td>
                    <span>
                        @coupon.StartDate.ToShortDateString()
                    </span>
                </td>
                <td>
                    <span>
                        @coupon.EndDate.ToShortDateString()
                    </span>
                </td>
            </tr>
        }
    </tbody>
</table>

@*Chi tiet hoa don*@


<h2>Payment Detail</h2>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Hình ảnh</th>
            <th>Sản phẩm</th>
            <th>Loai</th>
            <th>Số lượng</th>
            <th>Giá</th>
            <th>Tạm tính</th>
            <th>Khuyến mãi</th>
            <th>Giá cuối cùng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Item1.Items)
        {

            var coupon = Model.Item2.FirstOrDefault(c => c.CategoryId == item.CategoryId);

            discount = coupon != null ? coupon.Discount : 0;
            cost = item.Price * (1 - (discount / 100)) * item.Quantity;

            sumTotal += (item.Price * item.Quantity);
            discountTotal += cost;
            <tr>
                <td>
                    <a class="text-decoration-none text-black" asp-controller="Product" asp-action="Display" asp-route-productId="@item.ProductId">
                        <img src="@item.ImageUrl" alt="@item.Name" style="width:100px;height:auto;">
                    </a>
                </td>
                <td>
                    <a class="text-decoration-none text-black" asp-controller="Product" asp-action="Display" asp-route-productId="@item.ProductId">
                        @Html.DisplayFor(modelItem => item.Name)
                    </a>
                </td>
                <td>
                    <a class="text-decoration-none text-black" asp-controller="Product" asp-action="Display" asp-route-productId="@item.ProductId">
                        @Model.Item4.FirstOrDefault(c => c.Id == item.CategoryId)?.Name
                    </a>
                </td>
                <td>
                    <a class="text-decoration-none text-black" asp-controller="Product" asp-action="Display" asp-route-productId="@item.ProductId">
                        @item.Quantity
                    </a>
                </td>
                <td>@Html.DisplayFor(modelItem => item.Price)</td> @* gia *@
                <td>@(item.Price * item.Quantity)</td>             @* tam tinh *@
                <td>@discount %</td>                       @* khuyen mai *@
                <td>@cost</td>                                     @* gia cuoi cung *@
            </tr>

        }
        @{
            sumTotal = sumTotal / 2;
        }
    </tbody>
</table>

<div class="my-4 d-flex justify-content-between">
    <div>
        <h1> </h1>
    </div>
    <div>
        <p class="fw-bold">Tổng tiền tạm tính: @sumTotal.ToString("N0") VND</p>
        <p class="fw-bold">Tổng tiền cuối cùng: @discountTotal.ToString("N0") VND</p>
    </div>
</div>

<div class="my-4 d-flex justify-content-between">
    <form action="@Url.Action("Checkout", "ShoppingCart")" >
        <input type="hidden" name="discountTotal" value="@discountTotal" />
        <button type="submit" class="btn btn-success">Tiến hành đặt hàng</button>
    </form>
     <a asp-action="OrderList" asp-controller="ShoppingCart" class="btn btn-info">Đơn hàng của bạn</a>
</div>

WebsiteFashion/Views/ShoppingCart/OrderCompleted.cshtml
@model int
<h2>Order Completed</h2>
<p>Your order with ID @Model has been placed successfully.</p>
<p>Price @Model</p>

WebsiteFashion/Views/ShoppingCart/OrderDetails.cshtml
@model WebsiteFashion.Models.Order
@{
    ViewData["Title"] = "OrderDetails";
}

<table class="table">
    <thead>
        <tr>
            <th>Sản phẩm</th>
            <th>Số lượng</th>
            <th>Giá</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var detail in Model.OrderDetails)
        {
            <tr>
                <td>@detail.Product.Name</td>
                <td>@detail.Quantity</td>
                <td>@detail.Price.ToString("N0")VND</td>
                <td>@((detail.Price * (detail.Quantity)).ToString("N0"))VND</td>
                
            </tr>
        }
    </tbody>
</table>

<div>
    <h3>Total: @Model.TotalPrice.ToString("C")</h3>
</div>

WebsiteFashion/Views/ShoppingCart/OrderList.cshtml
@model IEnumerable<WebsiteFashion.Models.Order>

@{
    ViewData["Title"] = "Order List";
}

<h2>Your Order History</h2>

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Total Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    <td>@order.Id</td>
                    <td>@order.OrderDate.ToString("dd/MM/yyyy")</td>
                    <td>@order.TotalPrice.ToString("C")</td>
                    <td>
                        <!-- Link đến trang chi tiết đơn hàng -->
                        <a href="@Url.Action("OrderDetails", "ShoppingCart", new { orderId = order.Id })">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>@ViewBag.Message</p>
}

WebsiteFashion/Views/ShoppingCart/PaymentFail.cshtml
@{
	ViewData["Title"] = "Payment Fail";
}

<div class="container-fluid contact py-5">
	<div class="container">
		<div class="p-5 bg-light rounded">
			<div class="row g-4">
				<div class="col-12">
					<div class="text-center mx-auto" style="max-width: 700px;">
						<h1 class="text-primary">Payment Fail</h1>
						<h3 class="text-danger">@TempData["Message"]</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

WebsiteFashion/Views/ShoppingCart/PaymentSuccess.cshtml
@{
	ViewData["Title"] = "Payment Success";
}

<div class="container-fluid contact py-5">
	<div class="container">
		<div class="p-5 bg-light rounded">
			<div class="row g-4">
				<div class="col-12">
					<div class="text-center mx-auto" style="max-width: 700px;">
						<h1 class="text-primary">Payment Success</h1>
						<h3 class="text-danger">@TempData["Message"]</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>